from app.ai_engine.providers.base import AIExplanationProvider
from app.ai_engine.schemas import AIExplanationRequest, AIExplanationResponse


class MockAIExplanationProvider(AIExplanationProvider):
    """Mock AI provider used before integrating a real AI model."""

    def generate_explanation(
        self,
        request: AIExplanationRequest,
    ) -> AIExplanationResponse:
        reason_text = ", ".join(request.reason_codes)

        beginner_summary = (
            "This explanation is generated by the mock AI provider. "
            "It uses structured recommendation data from the backend and turns "
            "it into beginner-friendly language."
        )

        explanation = (
            f"The system suggested the action '{request.suggested_action}' "
            f"with an amount of ₹{request.suggested_amount}. "
            f"The main reason codes considered were: {reason_text}. "
            f"In simple terms, the recommendation means: {request.summary}"
        )

        risk_explanation = (
            "The risk section explains what the backend risk engine found. "
            f"{request.risk_note}"
        )

        return AIExplanationResponse(
            provider="MOCK",
            explanation=explanation,
            beginner_summary=beginner_summary,
            risk_explanation=risk_explanation,
        )