from app.ai_engine.providers.base import AIExplanationProvider
from app.ai_engine.schemas import AIExplanationRequest, AIExplanationResponse


class MockAIExplanationProvider(AIExplanationProvider):
    """Mock AI provider used before integrating a real AI model."""

    def generate_explanation(
        self,
        request: AIExplanationRequest,
    ) -> AIExplanationResponse:
        reason_text = ", ".join(request.reason_codes)

        if request.allocation_plan:
            allocation_text = ", ".join(
                [
                    f"{item.instrument_type}: ₹{item.amount}"
                    for item in request.allocation_plan
                ]
            )
        else:
            allocation_text = "No allocation plan was provided."

        if request.score_breakdown is not None:
            score_text = (
                f"Diversification: "
                f"{request.score_breakdown.diversification_score}/100, "
                f"Risk suitability: "
                f"{request.score_breakdown.risk_suitability_score}/100, "
                f"Preference match: "
                f"{request.score_breakdown.preference_match_score}/100."
            )
        else:
            score_text = "No score breakdown was provided."

        beginner_summary = (
            "This explanation is generated by the mock AI provider. "
            "It uses structured recommendation data, allocation details, "
            "and score breakdown from the backend."
        )

        explanation = (
            f"The system suggested the action '{request.suggested_action}' "
            f"with an amount of ₹{request.suggested_amount}. "
            f"The main reason codes considered were: {reason_text}. "
            f"The suggested allocation is: {allocation_text}. "
            f"The score breakdown is: {score_text} "
            f"In simple terms, the recommendation means: {request.summary}"
        )

        risk_explanation = (
            "The risk section explains what the backend risk engine found. "
            f"{request.risk_note}"
        )

        return AIExplanationResponse(
            provider="MOCK",
            explanation=explanation,
            beginner_summary=beginner_summary,
            risk_explanation=risk_explanation,
        )