from enum import Enum


class RecommendationAction(str, Enum):
    CONTINUE_DISCIPLINED_INVESTING = "CONTINUE_DISCIPLINED_INVESTING"
    COMPLETE_PROFILE_FIRST = "COMPLETE_PROFILE_FIRST"
    ADD_PORTFOLIO_FIRST = "ADD_PORTFOLIO_FIRST"
    REVIEW_PORTFOLIO_DIVERSIFICATION = "REVIEW_PORTFOLIO_DIVERSIFICATION"
    DIVERSIFY_MONTHLY_INVESTMENT = "DIVERSIFY_MONTHLY_INVESTMENT"


class RecommendationReasonCode(str, Enum):
    PROFILE_AVAILABLE = "PROFILE_AVAILABLE"
    PROFILE_MISSING = "PROFILE_MISSING"
    PORTFOLIO_AVAILABLE = "PORTFOLIO_AVAILABLE"
    PORTFOLIO_EMPTY = "PORTFOLIO_EMPTY"
    BEGINNER_LONG_TERM_APPROACH = "BEGINNER_LONG_TERM_APPROACH"
    MONTHLY_DISCIPLINE = "MONTHLY_DISCIPLINE"
    PORTFOLIO_CONCENTRATION_WARNING = "PORTFOLIO_CONCENTRATION_WARNING"
    DIVERSIFICATION_REVIEW_NEEDED = "DIVERSIFICATION_REVIEW_NEEDED"
    RISK_PROFILE_CONSIDERED = "RISK_PROFILE_CONSIDERED"
    PREFERRED_INSTRUMENTS_CONSIDERED = "PREFERRED_INSTRUMENTS_CONSIDERED"
    ALLOCATION_PLAN_CREATED = "ALLOCATION_PLAN_CREATED"
    RESEARCH_CONTEXT_INCLUDED = "RESEARCH_CONTEXT_INCLUDED"
    RESEARCH_CONTEXT_UNAVAILABLE = "RESEARCH_CONTEXT_UNAVAILABLE"
