from enum import Enum


class RecommendationAction(str, Enum):
    CONTINUE_DISCIPLINED_INVESTING = "CONTINUE_DISCIPLINED_INVESTING"
    COMPLETE_PROFILE_FIRST = "COMPLETE_PROFILE_FIRST"
    ADD_PORTFOLIO_FIRST = "ADD_PORTFOLIO_FIRST"
    REVIEW_PORTFOLIO = "REVIEW_PORTFOLIO"


class RecommendationReasonCode(str, Enum):
    PROFILE_AVAILABLE = "PROFILE_AVAILABLE"
    PROFILE_MISSING = "PROFILE_MISSING"
    PORTFOLIO_AVAILABLE = "PORTFOLIO_AVAILABLE"
    PORTFOLIO_EMPTY = "PORTFOLIO_EMPTY"
    BEGINNER_LONG_TERM_APPROACH = "BEGINNER_LONG_TERM_APPROACH"
    MONTHLY_DISCIPLINE = "MONTHLY_DISCIPLINE"
