"""baseline existing schema

Revision ID: 945ae04ce1a3
Revises: 
Create Date: 2026-06-08 16:04:49.709129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945ae04ce1a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument_master', sa.Column('history_status', sa.String(), nullable=True))
    op.add_column('instrument_master', sa.Column('history_provider', sa.String(), nullable=True))
    op.add_column('instrument_master', sa.Column('history_last_available_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instrument_master', sa.Column('history_last_refresh_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instrument_master', sa.Column('history_last_refresh_success_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instrument_master', sa.Column('history_error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument_master', 'history_error_message')
    op.drop_column('instrument_master', 'history_last_refresh_success_at')
    op.drop_column('instrument_master', 'history_last_refresh_attempt_at')
    op.drop_column('instrument_master', 'history_last_available_date')
    op.drop_column('instrument_master', 'history_provider')
    op.drop_column('instrument_master', 'history_status')
    # ### end Alembic commands ###
